---
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Update packages
    yum:
      name: '*'
      state: latest

  - name: Install common packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - ansible
    - 'http://dl.fedoraproject.org/pub/epel/testing/7/x86_64/c/copr-cli-1.60-1.el7.noarch.rpm'
    - git
    - java-1.8.0-openjdk
    - net-tools
