---
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Create jenkins repo
    yum_repository:
      name: "jenkins"
      description: "Jenkins Stable Repo"
      baseurl: "http://pkg.jenkins.io/redhat-stable"
      enabled: yes
      gpgcheck: yes
      gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

  - name: Update packages
    yum:
      name: '*'
      state: latest

  - name: Install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - java-1.8.0-openjdk
    - git
    - 'http://dl.fedoraproject.org/pub/epel/testing/7/x86_64/c/copr-cli-1.60-1.el7.noarch.rpm'
    - ansible
    - docker

  - name: Configure docker storage
    copy:
      content: |
               STORAGE_DRIVER=""
      dest: /etc/sysconfig/docker-storage-setup

  - name: Start docker
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: Start firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
