---
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Configure epel repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: Update packages
    yum:
      name: '*'
      state: latest

  - name: Enable repos for RHEL in AWS
    shell: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
    when: ansible_distribution == 'RedHat'

  - name: Install common packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - ansible
    - copr-cli
    - firewalld
    - git
    - java-1.8.0-openjdk
    - net-tools
    - python-pip
