---
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Create jenkins repo
    yum_repository:
      name: "jenkins"
      description: "Jenkins Stable Repo"
      baseurl: "http://pkg.jenkins.io/redhat-stable"
      enabled: yes
      gpgcheck: yes
      gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

  - name: Update packages
    yum:
      name: '*'
      state: latest

  - name: Install packages
    yum:
      name: java-1.8.0-openjdk
      state: latest

  - name: Start firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
