---
  - name: Create jenkins repo
    yum_repository:
      name: "jenkins"
      description: "Jenkins Stable Repo"
      baseurl: "http://pkg.jenkins.io/redhat-stable"
      enabled: yes
      gpgcheck: yes
      gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

  - name: Install master packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - certbot
    - jenkins
    - libsemanage-python
    - nginx
    - openssl
    - py-bcrypt

  - block:
    - debug:
        msg: #Set up certbot, configure nginx, do systemctl enable --now certbot-renew.timer
    when:
    - vagrant is not defined
    - letsencrypt

  - name: Create self-signed SSL cert
    command: openssl req -new -nodes -x509 -subj "/C=US/ST=North Carolina/L=Raleigh/O=Jenkins/CN={{ inventory_hostname }}" -days 3650 -keyout /etc/ssl/certs/jenkins.key -out /etc/ssl/certs/jenkins.crt -extensions v3_ca
    args:
      creates: /etc/ssl/certs/jenkins.crt
    when:
    - custom_cert_file is not defined
    - custom_key_file is not defined
    - not letsencrypt

  - name: Configure nginx
    template:
      src: "{{ role_path }}/templates/etc/nginx/nginx.conf.j2"
      dest: /etc/nginx/nginx.conf

  - name: Configure jenkins
    copy:
      src: "{{ role_path }}/files/var/lib/jenkins/config.xml"
      dest: /var/lib/jenkins/config.xml
      owner: jenkins
      group: jenkins

  - name: Set jenkins options
    copy:
      src: "{{ role_path }}/files/etc/sysconfig/jenkins"
      dest: /etc/sysconfig/jenkins

  - name: Generate jenkins admin users password hash
    shell: python -c 'import bcrypt; print(bcrypt.hashpw("{{ jenkins_admin_passwd }}", bcrypt.gensalt(log_rounds=10)))'
    register: jenkins_admin_passwd_hash

  - name: Create directories
    file:
      path: "{{ item }}"
      mode: 0755
      state: directory
      owner: jenkins
      group: jenkins
    with_items:
    - /var/lib/jenkins/users/admin
    - /var/lib/jenkins/jobs/Copr-RPM-based-container-rebuild-template/
    - "/var/lib/jenkins/jobs/run-catasb/"

  - name: Configure jenkins admin user
    template:
      src: "{{ role_path }}/templates/var/lib/jenkins/users/admin/config.xml.j2"
      dest: /var/lib/jenkins/users/admin/config.xml
      owner: jenkins
      group: jenkins

  - name: Configure job template
    copy:
      src: "{{ role_path }}/files/var/lib/jenkins/jobs/Copr-RPM-based-container-rebuild-template/config.xml"
      dest: "/var/lib/jenkins/jobs/Copr-RPM-based-container-rebuild-template/config.xml"

  - name: Configure catasb job
    copy:
      src: "{{ role_path }}/files/var/lib/jenkins/jobs/run-catasb/config.xml"
      dest: "/var/lib/jenkins/jobs/run-catasb/config.xml"

  - name: Start master services
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
    - jenkins
    - nginx

  - name: Open http firewall access
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
    - 80/tcp
    - 443/tcp
    - 59730/tcp

  - name: Restart firewalld
    systemd:
      name: firewalld
      state: restarted

  - name: Allow nginx to network connect
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Wait for jenkins and nginx start
    uri:
      url: https://{{ inventory_hostname }}/login
      validate_certs: no
    register: result
    until: result.status == 200
    retries: 5
    delay: 3

  - name: Get jenkins client
    get_url:
      url: "https://localhost/jnlpJars/jenkins-cli.jar"
      dest: /root/jenkins-cli.jar
      mode: 0644
      validate_certs: no

  - name: Install plugins
    shell: java -jar /root/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin {{ item }} --username admin --password {{ jenkins_admin_passwd }}
    with_items:
    - ant
    - build-timeout
    - email-ext
    - github-branch-source
    - gradle
    - ssh-slaves
    - subversion
    - timestamper
    - workflow-aggregator
    - ws-cleanup

  - name: Disable cli remoting
    copy:
      src: "{{ role_path }}/files/var/lib/jenkins/jenkins.CLI.xml"
      dest: /var/lib/jenkins/jenkins.CLI.xml

  - name: Enable master to slave security
    copy:
      content: false
      dest: /var/lib/jenkins/secrets/slave-to-master-security-kill-switch
      owner: jenkins
      group: jenkins

  - name: Restart jenkins to load plugins
    systemd:
      name: jenkins
      state: restarted

  - name: Wait for jenkins start
    uri:
      url: https://{{ inventory_hostname }}/login
      validate_certs: no
    register: result
    until: result.status == 200
    retries: 5
    delay: 3

  - name: Obtain crumb
    uri:
      url: 'https://localhost/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
      user: admin
      password: "{{ jenkins_admin_passwd }}"
      force_basic_auth: yes
      return_content: yes
      validate_certs: no
    register: crumb

  - name: Create credentials for vagrant slaves
    uri:
      url: 'https://localhost/credentials/store/system/domain/_/createCredentials'
      method: POST
      user: admin
      password: "{{ jenkins_admin_passwd }}"
      body: json={{ lookup('template', 'api/credential.j2')|to_nice_json}}
      force_basic_auth: yes
      headers:
        Jenkins-Crumb: "{{ crumb.content | regex_replace('Jenkins-Crumb:') }}"
      status_code: 302
      validate_certs: no
    with_sequence: count={{ jenkins_slaves|int }}
    when: vagrant is defined

  - name: Create credentials for non-vagrant slaves
    uri:
      url: 'https://localhost/credentials/store/system/domain/_/createCredentials'
      method: POST
      user: admin
      password: "{{ jenkins_admin_passwd }}"
      body: json={{ lookup('template', 'api/credential.j2')|to_nice_json}}
      force_basic_auth: yes
      headers:
        Jenkins-Crumb: "{{ crumb.content | regex_replace('Jenkins-Crumb:') }}"
      status_code: 302
      validate_certs: no
    when: vagrant is not defined

  - set_fact:
      homedir: "/root"
    when: slave_ssh_username == "root"

  - set_fact:
      homedir: "/home/{{ slave_ssh_username }}"
    when: slave_ssh_username != "root"

  - name: Create nodes
    uri:
      url: 'https://localhost/computer/doCreateItem?name={{ item }}&type=hudson.slaves.DumbSlave'
      method: POST
      user: admin
      password: "{{ jenkins_admin_passwd }}"
      body: json={{ lookup('template', 'api/slave.j2')|to_nice_json}}
      force_basic_auth: yes
      headers:
        Jenkins-Crumb: "{{ crumb.content | regex_replace('Jenkins-Crumb:') }}"
      status_code: 302,400
      validate_certs: no
    with_items: "{{ groups.jenkins_slaves }}"
    when: "'jenkins_slaves' in groups"
